services:
   db:
      image: mysql:8.0
      container_name: lookfit_db
      restart: unless-stopped
      environment:
         MYSQL_DATABASE: ${DB_NAME}
         MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      volumes:
         - mysql_data:/var/lib/mysql
      networks:
         - lookfit_net

   backend:
      build:
         context: .
         dockerfile: backend/Dockerfile
      container_name: lookfit_backend
      restart: unless-stopped
      env_file:
         - .env
      environment:
         DB_HOST: db
         DB_NAME: ${DB_NAME}
         DB_USER: root
         DB_PASSWORD: ${DB_ROOT_PASSWORD}
         YII_BASE_URL: ""
         YII_ENV: prod
         YII_DEBUG: "0"
         SOCKS_PROXY: host.docker.internal:1080
         USE_SOCKS_PROXY: "1"
      extra_hosts:
         - "host.docker.internal:host-gateway"
      volumes:
         - ./backend/web/uploads:/var/www/html/backend/web/uploads
      networks:
         - lookfit_net
      depends_on:
         - db

   frontend:
      build:
         context: .
         dockerfile: frontend/Dockerfile
      container_name: lookfit_frontend
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - /etc/letsencrypt:/etc/letsencrypt:ro
      networks:
         - lookfit_net

volumes:
   mysql_data:

networks:
   lookfit_net:
      driver: bridge
